name: Java CI with Maven

on:
  push:
    branches: dev
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Dependencies
        run: |
            mvn install:install-file -Dfile=./Tour-Guide/libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1 -Dpackaging=jar
            mvn install:install-file -Dfile=./Tour-Guide/libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1 -Dpackaging=jar
            mvn install:install-file -Dfile=./Tour-Guide/libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1 -Dpackaging=jar

      - name: Build and test with Maven
        run: mvn package --batch-mode

      - name: Upload application JAR
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar
